---

- name: reload daemon
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: enable pod service
  ansible.builtin.systemd:
    name: pod-gitea
    enabled: true
    scope: user

- name: restart pod service
  ansible.builtin.systemd:
    name: pod-gitea
    state: restarted
    scope: user
